-record(uthought,
        {text,
         time,
         geo,
         insp,
         tags,
         source,
         vsn}).

-record(thought,
        {text,
         time,
         geo,
         insp,
         tags,
         source,
         vsn,
         sig,
         score}).
