-record(uthought,
        {text,
         time,
         geo,
         insp,
         tags,
         links,
         source}).

-record(thought,
        {sig,
         text,
         time,
         geo,
         insp,
         tags,
         links,
         source,
         score}).
